block.settings.custom_features_kit:
  type: block_settings
  label: 'Kit block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_cat:
  type: block_settings
  label: 'Cat block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_reference:
  type: block_settings
  label: 'Reference block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_another:
  type: block_settings
  label: 'Another block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_sample:
  type: block_settings
  label: 'Sample block'
  mapping:
    foo:
      type: string
      label: Foo
